discovery:
    container_name: discovery
    image: quay.io/coreos/etcd:v2.2.1
    net: host

ambassador:
    container_name: ambassador
    command: "--addr 0.0.0.0:29091 --cluster debug --advertise 127.0.0.1:29091 etcd://127.0.0.1:2379"
    environment:
        LOG_LEVEL: INFO
    image: jeffjen/ambd
    net: host
    ports:
        - "29091:29091"

register:
    container_name: register
    command: "--addr 0.0.0.0:29092 --cluster debug --advertise 127.0.0.1:2375 etcd://127.0.0.1:2379"
    image: jeffjen/docker-monitor
    net: host
    ports:
        - "29092:29092"
    volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"

redis:
    container_name: redis
    command: redis-server --port 16379
    image: redis
    labels:
        service: /srv/redis/debug
        port: "16379"
        probe_type: "redis"
    net: host

probe:
    build: .
    command: "node test.js"
    net: host
    working_dir: /usr/src/app
